[project]
name = "dreamworks"
version = "0.1.0"
dependencies = [
    "python-telegram-bot==20.8",
    "SQLAlchemy==2.0.35",
    "alembic==1.13.2",
    "openai==1.51.0",
    "pydantic==2.9.2",
    "python-dotenv==1.0.1"
]